approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 168h

npmRegistryServer: "https://registry.yarnpkg.com"

npmPreapprovedPackages: [
  "@sirenpm/core",
  "@sirenpm/language",
  "@sirenpm/cli"
]