approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: true

enableTransparentWorkspaces: false

nodeLinker: node-modules

npmMinimalAgeGate: 168h

npmRegistryServer: "https://registry.yarnpkg.com"
