/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_bare_identifier = 1,
  anon_sym_task = 2,
  anon_sym_milestone = 3,
  sym_block_open = 4,
  sym_block_close = 5,
  anon_sym_EQ = 6,
  sym_comment = 7,
  anon_sym_COMMA = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_string_literal_token1 = 12,
  anon_sym_DQUOTE2 = 13,
  sym_number_literal = 14,
  anon_sym_true = 15,
  anon_sym_false = 16,
  sym_document = 17,
  sym_resource_type = 18,
  sym_resource_modifier = 19,
  sym_resource_header = 20,
  sym_block = 21,
  sym_resource = 22,
  sym_identifier = 23,
  sym_attribute = 24,
  sym_tuple = 25,
  sym__tuple_member = 26,
  sym__implicit_tuple = 27,
  sym__explicit_tuple = 28,
  sym_expression = 29,
  sym_literal = 30,
  sym_string_literal = 31,
  sym_boolean_literal = 32,
  aux_sym_document_repeat1 = 33,
  aux_sym_resource_header_repeat1 = 34,
  aux_sym_block_repeat1 = 35,
  aux_sym__implicit_tuple_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_bare_identifier] = "bare_identifier",
  [anon_sym_task] = "task",
  [anon_sym_milestone] = "milestone",
  [sym_block_open] = "block_open",
  [sym_block_close] = "block_close",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "str_open",
  [aux_sym_string_literal_token1] = "str_body",
  [anon_sym_DQUOTE2] = "str_close",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_document] = "document",
  [sym_resource_type] = "resource_type",
  [sym_resource_modifier] = "resource_modifier",
  [sym_resource_header] = "resource_header",
  [sym_block] = "block",
  [sym_resource] = "resource",
  [sym_identifier] = "identifier",
  [sym_attribute] = "attribute",
  [sym_tuple] = "tuple",
  [sym__tuple_member] = "_tuple_member",
  [sym__implicit_tuple] = "_implicit_tuple",
  [sym__explicit_tuple] = "_explicit_tuple",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_resource_header_repeat1] = "resource_header_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym__implicit_tuple_repeat1] = "_implicit_tuple_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_bare_identifier] = sym_bare_identifier,
  [anon_sym_task] = anon_sym_task,
  [anon_sym_milestone] = anon_sym_milestone,
  [sym_block_open] = sym_block_open,
  [sym_block_close] = sym_block_close,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE2,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_document] = sym_document,
  [sym_resource_type] = sym_resource_type,
  [sym_resource_modifier] = sym_resource_modifier,
  [sym_resource_header] = sym_resource_header,
  [sym_block] = sym_block,
  [sym_resource] = sym_resource,
  [sym_identifier] = sym_identifier,
  [sym_attribute] = sym_attribute,
  [sym_tuple] = sym_tuple,
  [sym__tuple_member] = sym__tuple_member,
  [sym__implicit_tuple] = sym__implicit_tuple,
  [sym__explicit_tuple] = sym__explicit_tuple,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_resource_header_repeat1] = aux_sym_resource_header_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym__implicit_tuple_repeat1] = aux_sym__implicit_tuple_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_bare_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_task] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_milestone] = {
    .visible = true,
    .named = false,
  },
  [sym_block_open] = {
    .visible = true,
    .named = true,
  },
  [sym_block_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_literal_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_type] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_header] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_resource] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym__tuple_member] = {
    .visible = false,
    .named = true,
  },
  [sym__implicit_tuple] = {
    .visible = false,
    .named = true,
  },
  [sym__explicit_tuple] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resource_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__implicit_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_id = 2,
  field_key = 3,
  field_status_modifier = 4,
  field_type = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_id] = "id",
  [field_key] = "key",
  [field_status_modifier] = "status_modifier",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
    {field_type, 0},
  [2] =
    {field_body, 1},
  [3] =
    {field_id, 1},
    {field_status_modifier, 2},
    {field_type, 0},
  [6] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 14,
        '#', 10,
        ',', 11,
        '/', 3,
        '=', 9,
        '[', 12,
        ']', 13,
        '{', 6,
        '}', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_block_open);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_block_close);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_bare_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'm') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'k') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_task);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_milestone);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_bare_identifier] = ACTIONS(1),
    [anon_sym_task] = ACTIONS(1),
    [anon_sym_milestone] = ACTIONS(1),
    [sym_block_open] = ACTIONS(1),
    [sym_block_close] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(36),
    [sym_resource_type] = STATE(14),
    [sym_resource_header] = STATE(26),
    [sym_resource] = STATE(9),
    [aux_sym_document_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_task] = ACTIONS(7),
    [anon_sym_milestone] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_bare_identifier,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym_number_literal,
    STATE(29), 1,
      sym_tuple,
    STATE(31), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 2,
      sym__tuple_member,
      sym_literal,
    STATE(20), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(28), 2,
      sym__implicit_tuple,
      sym__explicit_tuple,
  [38] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_bare_identifier,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym_number_literal,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      sym__implicit_tuple,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 2,
      sym__tuple_member,
      sym_literal,
    STATE(20), 2,
      sym_string_literal,
      sym_boolean_literal,
  [69] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym_number_literal,
    ACTIONS(21), 1,
      sym_bare_identifier,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 2,
      sym__tuple_member,
      sym_literal,
    STATE(20), 2,
      sym_string_literal,
      sym_boolean_literal,
  [94] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_resource_type,
    STATE(26), 1,
      sym_resource_header,
    ACTIONS(25), 2,
      anon_sym_task,
      anon_sym_milestone,
    STATE(5), 2,
      sym_resource,
      aux_sym_document_repeat1,
  [115] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(28), 1,
      sym_bare_identifier,
    ACTIONS(30), 1,
      sym_block_open,
    STATE(23), 1,
      sym_identifier,
    STATE(24), 1,
      sym_string_literal,
    STATE(8), 2,
      sym_resource_modifier,
      aux_sym_resource_header_repeat1,
  [138] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym_bare_identifier,
    ACTIONS(35), 1,
      sym_block_open,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    STATE(23), 1,
      sym_identifier,
    STATE(24), 1,
      sym_string_literal,
    STATE(7), 2,
      sym_resource_modifier,
      aux_sym_resource_header_repeat1,
  [161] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(28), 1,
      sym_bare_identifier,
    ACTIONS(40), 1,
      sym_block_open,
    STATE(23), 1,
      sym_identifier,
    STATE(24), 1,
      sym_string_literal,
    STATE(7), 2,
      sym_resource_modifier,
      aux_sym_resource_header_repeat1,
  [184] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_resource_type,
    STATE(26), 1,
      sym_resource_header,
    ACTIONS(7), 2,
      anon_sym_task,
      anon_sym_milestone,
    STATE(5), 2,
      sym_resource,
      aux_sym_document_repeat1,
  [205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 6,
      sym_block_open,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
  [217] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym__implicit_tuple_repeat1,
    ACTIONS(46), 3,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_RBRACK,
  [232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym__implicit_tuple_repeat1,
    ACTIONS(50), 3,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_RBRACK,
  [247] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym__implicit_tuple_repeat1,
    ACTIONS(55), 3,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_RBRACK,
  [262] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(28), 1,
      sym_bare_identifier,
    STATE(6), 1,
      sym_identifier,
    STATE(24), 1,
      sym_string_literal,
  [278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_bare_identifier,
    ACTIONS(59), 1,
      sym_block_close,
    STATE(16), 2,
      sym_attribute,
      aux_sym_block_repeat1,
  [292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym_bare_identifier,
    ACTIONS(64), 1,
      sym_block_close,
    STATE(16), 2,
      sym_attribute,
      aux_sym_block_repeat1,
  [306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 4,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [316] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      sym_bare_identifier,
    ACTIONS(68), 1,
      sym_block_close,
    STATE(15), 2,
      sym_attribute,
      aux_sym_block_repeat1,
  [330] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 4,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [340] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 4,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [350] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      anon_sym_task,
      anon_sym_milestone,
  [359] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      anon_sym_task,
      anon_sym_milestone,
  [368] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 3,
      sym_block_open,
      sym_bare_identifier,
      anon_sym_DQUOTE,
  [377] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 3,
      sym_block_open,
      sym_bare_identifier,
      anon_sym_DQUOTE,
  [386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 3,
      ts_builtin_sym_end,
      anon_sym_task,
      anon_sym_milestone,
  [395] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym_block_open,
    STATE(25), 1,
      sym_block,
  [405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      sym_bare_identifier,
      anon_sym_DQUOTE,
  [413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 2,
      sym_block_close,
      sym_bare_identifier,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 2,
      sym_block_close,
      sym_bare_identifier,
  [429] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      sym_block_close,
      sym_bare_identifier,
  [437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      sym_block_close,
      sym_bare_identifier,
  [445] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 2,
      sym_block_close,
      sym_bare_identifier,
  [453] = 2,
    ACTIONS(96), 1,
      sym_comment,
    ACTIONS(98), 1,
      aux_sym_string_literal_token1,
  [460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_DQUOTE2,
  [467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_EQ,
  [474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
  [481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 69,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 138,
  [SMALL_STATE(8)] = 161,
  [SMALL_STATE(9)] = 184,
  [SMALL_STATE(10)] = 205,
  [SMALL_STATE(11)] = 217,
  [SMALL_STATE(12)] = 232,
  [SMALL_STATE(13)] = 247,
  [SMALL_STATE(14)] = 262,
  [SMALL_STATE(15)] = 278,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 306,
  [SMALL_STATE(18)] = 316,
  [SMALL_STATE(19)] = 330,
  [SMALL_STATE(20)] = 340,
  [SMALL_STATE(21)] = 350,
  [SMALL_STATE(22)] = 359,
  [SMALL_STATE(23)] = 368,
  [SMALL_STATE(24)] = 377,
  [SMALL_STATE(25)] = 386,
  [SMALL_STATE(26)] = 395,
  [SMALL_STATE(27)] = 405,
  [SMALL_STATE(28)] = 413,
  [SMALL_STATE(29)] = 421,
  [SMALL_STATE(30)] = 429,
  [SMALL_STATE(31)] = 437,
  [SMALL_STATE(32)] = 445,
  [SMALL_STATE(33)] = 453,
  [SMALL_STATE(34)] = 460,
  [SMALL_STATE(35)] = 467,
  [SMALL_STATE(36)] = 474,
  [SMALL_STATE(37)] = 481,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_header, 2, 0, 1),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resource_header_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_resource_header_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resource_header_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_header, 3, 0, 3),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__implicit_tuple, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__implicit_tuple_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__implicit_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__implicit_tuple, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_modifier, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource, 2, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_type, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__explicit_tuple, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__explicit_tuple, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [104] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_siren(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_bare_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "siren",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
