/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_bare_identifier = 1,
  anon_sym_task = 2,
  anon_sym_milestone = 3,
  sym_block_open = 4,
  sym_block_close = 5,
  anon_sym_document = 6,
  anon_sym_EQ = 7,
  sym_comment = 8,
  anon_sym_COMMA = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_string_literal_token1 = 13,
  anon_sym_DQUOTE2 = 14,
  sym_number_literal = 15,
  anon_sym_true = 16,
  anon_sym_false = 17,
  sym_document = 18,
  sym_resource_type = 19,
  sym_resource_modifier = 20,
  sym_resource_header = 21,
  sym_block = 22,
  sym_resource = 23,
  sym_doc_header = 24,
  sym_identifier = 25,
  sym_attribute = 26,
  sym_tuple = 27,
  sym__tuple_member = 28,
  sym__implicit_tuple = 29,
  sym__explicit_tuple = 30,
  sym_expression = 31,
  sym_literal = 32,
  sym_string_literal = 33,
  sym_boolean_literal = 34,
  aux_sym_document_repeat1 = 35,
  aux_sym_resource_header_repeat1 = 36,
  aux_sym_block_repeat1 = 37,
  aux_sym__implicit_tuple_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_bare_identifier] = "bare_identifier",
  [anon_sym_task] = "task",
  [anon_sym_milestone] = "milestone",
  [sym_block_open] = "block_open",
  [sym_block_close] = "block_close",
  [anon_sym_document] = "document",
  [anon_sym_EQ] = "=",
  [sym_comment] = "comment",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "str_open",
  [aux_sym_string_literal_token1] = "str_body",
  [anon_sym_DQUOTE2] = "str_close",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_document] = "document",
  [sym_resource_type] = "resource_type",
  [sym_resource_modifier] = "resource_modifier",
  [sym_resource_header] = "resource_header",
  [sym_block] = "block",
  [sym_resource] = "resource",
  [sym_doc_header] = "doc_header",
  [sym_identifier] = "identifier",
  [sym_attribute] = "attribute",
  [sym_tuple] = "tuple",
  [sym__tuple_member] = "_tuple_member",
  [sym__implicit_tuple] = "_implicit_tuple",
  [sym__explicit_tuple] = "_explicit_tuple",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_resource_header_repeat1] = "resource_header_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym__implicit_tuple_repeat1] = "_implicit_tuple_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_bare_identifier] = sym_bare_identifier,
  [anon_sym_task] = anon_sym_task,
  [anon_sym_milestone] = anon_sym_milestone,
  [sym_block_open] = sym_block_open,
  [sym_block_close] = sym_block_close,
  [anon_sym_document] = anon_sym_document,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_comment] = sym_comment,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE2,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_document] = sym_document,
  [sym_resource_type] = sym_resource_type,
  [sym_resource_modifier] = sym_resource_modifier,
  [sym_resource_header] = sym_resource_header,
  [sym_block] = sym_block,
  [sym_resource] = sym_resource,
  [sym_doc_header] = sym_doc_header,
  [sym_identifier] = sym_identifier,
  [sym_attribute] = sym_attribute,
  [sym_tuple] = sym_tuple,
  [sym__tuple_member] = sym__tuple_member,
  [sym__implicit_tuple] = sym__implicit_tuple,
  [sym__explicit_tuple] = sym__explicit_tuple,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_resource_header_repeat1] = aux_sym_resource_header_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym__implicit_tuple_repeat1] = aux_sym__implicit_tuple_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_bare_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_task] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_milestone] = {
    .visible = true,
    .named = false,
  },
  [sym_block_open] = {
    .visible = true,
    .named = true,
  },
  [sym_block_close] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_document] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_literal_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_type] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_header] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_resource] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_header] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym__tuple_member] = {
    .visible = false,
    .named = true,
  },
  [sym__implicit_tuple] = {
    .visible = false,
    .named = true,
  },
  [sym__explicit_tuple] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resource_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__implicit_tuple_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_id = 2,
  field_key = 3,
  field_status_modifier = 4,
  field_type = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_id] = "id",
  [field_key] = "key",
  [field_status_modifier] = "status_modifier",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
    {field_type, 0},
  [2] =
    {field_body, 1},
  [3] =
    {field_id, 1},
    {field_status_modifier, 2},
    {field_type, 0},
  [6] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 23,
  [34] = 24,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '"', 14,
        '#', 10,
        ',', 11,
        '/', 3,
        '=', 9,
        '[', 12,
        ']', 13,
        '{', 6,
        '}', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_block_open);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_block_close);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_bare_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'm') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'k') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_task);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_document);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_milestone);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_bare_identifier] = ACTIONS(1),
    [anon_sym_task] = ACTIONS(1),
    [anon_sym_milestone] = ACTIONS(1),
    [sym_block_open] = ACTIONS(1),
    [sym_block_close] = ACTIONS(1),
    [anon_sym_document] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(46),
    [sym_resource_type] = STATE(25),
    [sym_resource_header] = STATE(38),
    [sym_resource] = STATE(12),
    [sym_doc_header] = STATE(15),
    [aux_sym_document_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_task] = ACTIONS(7),
    [anon_sym_milestone] = ACTIONS(7),
    [anon_sym_document] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_bare_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_number_literal,
    STATE(37), 1,
      sym_tuple,
    STATE(41), 1,
      sym_expression,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(23), 2,
      sym__tuple_member,
      sym_literal,
    STATE(42), 2,
      sym__implicit_tuple,
      sym__explicit_tuple,
  [38] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_number_literal,
    ACTIONS(21), 1,
      sym_bare_identifier,
    ACTIONS(23), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      sym__implicit_tuple,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(33), 2,
      sym__tuple_member,
      sym_literal,
  [69] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_number_literal,
    ACTIONS(25), 1,
      sym_bare_identifier,
    ACTIONS(28), 1,
      sym_block_close,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(26), 2,
      sym__tuple_member,
      sym_literal,
  [97] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_number_literal,
    ACTIONS(30), 1,
      sym_bare_identifier,
    ACTIONS(33), 1,
      sym_block_close,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(26), 2,
      sym__tuple_member,
      sym_literal,
  [125] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_number_literal,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 1,
      sym_bare_identifier,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(26), 2,
      sym__tuple_member,
      sym_literal,
  [153] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_number_literal,
    ACTIONS(28), 1,
      anon_sym_RBRACK,
    ACTIONS(35), 1,
      sym_bare_identifier,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(26), 2,
      sym__tuple_member,
      sym_literal,
  [181] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_number_literal,
    ACTIONS(35), 1,
      sym_bare_identifier,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(26), 2,
      sym__tuple_member,
      sym_literal,
  [206] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_resource_type,
    STATE(38), 1,
      sym_resource_header,
    ACTIONS(7), 2,
      anon_sym_task,
      anon_sym_milestone,
    STATE(14), 2,
      sym_resource,
      aux_sym_document_repeat1,
  [227] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      sym_bare_identifier,
    ACTIONS(41), 1,
      sym_block_open,
    STATE(28), 1,
      sym_string_literal,
    STATE(29), 1,
      sym_identifier,
    STATE(13), 2,
      sym_resource_modifier,
      aux_sym_resource_header_repeat1,
  [250] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      sym_bare_identifier,
    ACTIONS(43), 1,
      sym_block_open,
    STATE(28), 1,
      sym_string_literal,
    STATE(29), 1,
      sym_identifier,
    STATE(10), 2,
      sym_resource_modifier,
      aux_sym_resource_header_repeat1,
  [273] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_resource_type,
    STATE(38), 1,
      sym_resource_header,
    ACTIONS(7), 2,
      anon_sym_task,
      anon_sym_milestone,
    STATE(14), 2,
      sym_resource,
      aux_sym_document_repeat1,
  [294] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      sym_bare_identifier,
    ACTIONS(50), 1,
      sym_block_open,
    ACTIONS(52), 1,
      anon_sym_DQUOTE,
    STATE(28), 1,
      sym_string_literal,
    STATE(29), 1,
      sym_identifier,
    STATE(13), 2,
      sym_resource_modifier,
      aux_sym_resource_header_repeat1,
  [317] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_resource_type,
    STATE(38), 1,
      sym_resource_header,
    ACTIONS(57), 2,
      anon_sym_task,
      anon_sym_milestone,
    STATE(14), 2,
      sym_resource,
      aux_sym_document_repeat1,
  [338] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_resource_type,
    STATE(38), 1,
      sym_resource_header,
    ACTIONS(7), 2,
      anon_sym_task,
      anon_sym_milestone,
    STATE(9), 2,
      sym_resource,
      aux_sym_document_repeat1,
  [359] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 6,
      sym_block_open,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
  [371] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym__implicit_tuple_repeat1,
    ACTIONS(62), 3,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_RBRACK,
  [386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 4,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [396] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_bare_identifier,
    ACTIONS(71), 1,
      sym_block_close,
    STATE(20), 2,
      sym_attribute,
      aux_sym_block_repeat1,
  [410] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_bare_identifier,
    ACTIONS(76), 1,
      sym_block_close,
    STATE(20), 2,
      sym_attribute,
      aux_sym_block_repeat1,
  [424] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym_bare_identifier,
    ACTIONS(78), 1,
      sym_block_close,
    STATE(19), 2,
      sym_attribute,
      aux_sym_block_repeat1,
  [438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 4,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [448] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym__implicit_tuple_repeat1,
    ACTIONS(82), 2,
      sym_block_close,
      sym_bare_identifier,
  [462] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym__implicit_tuple_repeat1,
    ACTIONS(33), 2,
      sym_block_close,
      sym_bare_identifier,
  [476] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      sym_bare_identifier,
    STATE(11), 1,
      sym_identifier,
    STATE(28), 1,
      sym_string_literal,
  [492] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 4,
      sym_block_close,
      sym_bare_identifier,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      anon_sym_task,
      anon_sym_milestone,
  [511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 3,
      sym_block_open,
      sym_bare_identifier,
      anon_sym_DQUOTE,
  [520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 3,
      sym_block_open,
      sym_bare_identifier,
      anon_sym_DQUOTE,
  [529] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      anon_sym_task,
      anon_sym_milestone,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      anon_sym_task,
      anon_sym_milestone,
  [547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 3,
      ts_builtin_sym_end,
      anon_sym_task,
      anon_sym_milestone,
  [556] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_RBRACK,
    ACTIONS(100), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym__implicit_tuple_repeat1,
  [569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym__implicit_tuple_repeat1,
  [582] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 2,
      sym_bare_identifier,
      anon_sym_DQUOTE,
  [590] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_block_open,
    STATE(27), 1,
      sym_block,
  [600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 2,
      sym_block_close,
      sym_bare_identifier,
  [608] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_block_open,
    STATE(31), 1,
      sym_block,
  [618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 2,
      sym_block_close,
      sym_bare_identifier,
  [626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 2,
      sym_block_close,
      sym_bare_identifier,
  [634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 2,
      sym_block_close,
      sym_bare_identifier,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 2,
      sym_block_close,
      sym_bare_identifier,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_DQUOTE2,
  [657] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_EQ,
  [664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_RBRACK,
  [671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
  [678] = 2,
    ACTIONS(126), 1,
      sym_comment,
    ACTIONS(128), 1,
      aux_sym_string_literal_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 69,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 125,
  [SMALL_STATE(7)] = 153,
  [SMALL_STATE(8)] = 181,
  [SMALL_STATE(9)] = 206,
  [SMALL_STATE(10)] = 227,
  [SMALL_STATE(11)] = 250,
  [SMALL_STATE(12)] = 273,
  [SMALL_STATE(13)] = 294,
  [SMALL_STATE(14)] = 317,
  [SMALL_STATE(15)] = 338,
  [SMALL_STATE(16)] = 359,
  [SMALL_STATE(17)] = 371,
  [SMALL_STATE(18)] = 386,
  [SMALL_STATE(19)] = 396,
  [SMALL_STATE(20)] = 410,
  [SMALL_STATE(21)] = 424,
  [SMALL_STATE(22)] = 438,
  [SMALL_STATE(23)] = 448,
  [SMALL_STATE(24)] = 462,
  [SMALL_STATE(25)] = 476,
  [SMALL_STATE(26)] = 492,
  [SMALL_STATE(27)] = 502,
  [SMALL_STATE(28)] = 511,
  [SMALL_STATE(29)] = 520,
  [SMALL_STATE(30)] = 529,
  [SMALL_STATE(31)] = 538,
  [SMALL_STATE(32)] = 547,
  [SMALL_STATE(33)] = 556,
  [SMALL_STATE(34)] = 569,
  [SMALL_STATE(35)] = 582,
  [SMALL_STATE(36)] = 590,
  [SMALL_STATE(37)] = 600,
  [SMALL_STATE(38)] = 608,
  [SMALL_STATE(39)] = 618,
  [SMALL_STATE(40)] = 626,
  [SMALL_STATE(41)] = 634,
  [SMALL_STATE(42)] = 642,
  [SMALL_STATE(43)] = 650,
  [SMALL_STATE(44)] = 657,
  [SMALL_STATE(45)] = 664,
  [SMALL_STATE(46)] = 671,
  [SMALL_STATE(47)] = 678,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__implicit_tuple, 3, 0, 0), SHIFT(26),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__implicit_tuple, 3, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__implicit_tuple, 2, 0, 0), SHIFT(26),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__implicit_tuple, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_header, 3, 0, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_header, 2, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resource_header_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_resource_header_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resource_header_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__implicit_tuple_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__implicit_tuple_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__implicit_tuple, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_header, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_modifier, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource, 2, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resource_type, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__explicit_tuple, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__explicit_tuple, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [124] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_siren(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_bare_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "siren",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
